#!/usr/bin/env bash

cat << "EOF"
 ___     ____                             _             _   
|_ _|   |  _ \  ___ _ __ ___  _ __   ___ | |_ ___ _ __ | |_ 
 | |    | | | |/ _ \ '_ ` _ \| '_ \ / _ \| __/ _ \ '_ \| __|
 | | _  | |_| |  __/ | | | | | |_) | (_) | ||  __/ | | | |_ 
|___( ) |____/ \___|_| |_| |_| .__/ \___/ \__\___|_| |_|\__|
    |/                       |_|                            

EOF

set -e -o pipefail -p

# Keep the computer awake for the duration of this script.
[[ $(command -v caffeinate) ]] && caffeinate -dusw $$ &

# Ask for the administrator password
sudo -v

# sudo keep-alive
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# INT/TERM trap
trap 'exit 1' INT TERM

if [[ $(uname -a) == *Darwin* ]] && [[ ! $(command -v brew) ]]; then
  echo "Installing Homebrew"

  # If we're using APFS, make a snapshot before doing anything.
  if [[ ! -z "$(mount | grep '/ (apfs')" ]]; then
    sudo tmutil enable
    sudo tmutil localsnapshot
  fi

  [[ $(command -v xcodebuild) ]] && sudo xcodebuild -license accept
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
elif [[ $(uname -a) == *Microsoft* ]]; then
  # WSL
  sudo apt update -y
  sudo apt upgrade -y
  sudo apt-get install -y build-essential curl file git python-setuptools ruby
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  echo "export HOMEBREW_BUILD_FROM_SOURCE=1" >> ~/.bash_profile
  . ~/.bash_profile
fi

export ICLOUD_DRIVE=$(
if [[ -e "$HOME/Library/Mobile Documents/com~apple~CloudDocs" ]]; then
  echo "$HOME/Library/Mobile Documents/com~apple~CloudDocs" # macOS
elif [[ -e "$(pwd)/iCloudDrive" ]]; then
  echo "$(pwd)/iCloudDrive" # Windows 10
else
  echo ""
fi
)

if [[ -f "$ICLOUD_DRIVE/.secrets" ]]; then
  source "$ICLOUD_DRIVE/.secrets"
  SECRETS_LOADED=1
  echo "Loaded secrets file from $ICLOUD_DRIVE/.secrets."
else
  echo "No secrets file has been loaded. Some things might break."
fi

# iCloud Drive links
if [[ -e $ICLOUD_DRIVE ]] && [[ ! -e ~/.ssh ]]; then
  if [[ -e $ICLOUD_DRIVE/ssh ]]; then
    ln -s "$ICLOUD_DRIVE/ssh" ~/.ssh
  fi

  chmod 700 ~/.ssh
  chmod -R 600 ~/.ssh/*
  chmod 644 ~/.ssh/authorized_keys
fi

if [[ -e ~/.config/.git/config ]] && [[ $(cat ~/.config/.git/config | grep github.com:LukeChannings/.config) ]]; then
  cd ~/.config
  git pull
  cd -
else
  echo 'Linking config files for programs not using $XDG_CONFIG_HOME'
  if [[ -e ~/.config ]]; then
    echo "Found existing ~/.config, moving it to ~/.config.old"
    mv ~/.config ~/.config.old
  fi
  git clone git@github.com:LukeChannings/.config.git ~/.config
fi

if [[ $(uname -s) == 'Darwin' ]]; then
  ~/.config/install.macos
fi

if [[ $(uname -s) == 'Linux' ]]; then
  ~/.config/install.linux
fi

ln -Fs /usr/local/bin/nvim /usr/local/bin/vim
fish -c 'fundle install'

# Set FISH as default shell
echo "$(brew --prefix)/bin/fish" | sudo tee -a /etc/shells
sudo chsh -s $(brew --prefix)/bin/fish $(whoami)

ln -fs ~/.config/editorconfig ~/.editorconfig
ln -fs ~/.config/tern/tern_config ~/.tern-config
ln -fs ~/.config/tmux/config ~/.tmux.conf

# Install global node packages
npm i -g http-server prettier

# Set up Neovim
if [[ $SECRETS_LOADED ]]; then

cat > ~/.wakatime.cfg << EOF
[settings]
debug = false
hidefilenames = false
ignore =
  COMMIT_EDITMSG$
  PULLREQ_EDITMSG$
  MERGE_MSG$
  TAG_EDITMSG$
api_key=$WAKATIME_API_KEY
EOF

fi

pip2 install neovim
pip3 install neovim

vim +PlugUpgrade +PlugInstall +qall

cd ~/.local/share/nvim/plugged/tern_for_vim
  npm i
cd -

cd ~/.local/share/nvim/plugged/YouCompleteMe
  ./install.py --tern-completer
cd -

