#!/usr/bin/env bash

cat << "EOF"
 ___     ____                             _             _   
|_ _|   |  _ \  ___ _ __ ___  _ __   ___ | |_ ___ _ __ | |_ 
 | |    | | | |/ _ \ '_ ` _ \| '_ \ / _ \| __/ _ \ '_ \| __|
 | | _  | |_| |  __/ | | | | | |_) | (_) | ||  __/ | | | |_ 
|___( ) |____/ \___|_| |_| |_| .__/ \___/ \__\___|_| |_|\__|
    |/                       |_|                            

EOF

set -e -o pipefail -p

# iCloud Drive links
if [ -e ~/Library/Mobile\ Documents/com~apple~CloudDocs/ssh ] && [ ! -e ~/.ssh ]; then
  ln -Fs ~/Library/Mobile\ Documents/com~apple~CloudDocs/ssh ~/.ssh
  chmod 700 ~/.ssh
  chmod -R 600 ~/.ssh/*
  chmod 644 ~/.ssh/authorized_keys
fi

if [[ ! $(cat ~/.config/.git/config | grep github.com:LukeChannings/.config) ]]; then
  echo Linking config files for programs not using \$XDG_CONFIG_HOME
  if [ -e ~/.config ]; then mv ~/.config ~/.config.old; fi
  git clone git@github.com:LukeChannings/.config.git ~/.config
fi

if [[ $(uname -s) == 'Darwin' ]]; then
  chmod +x ~/.config/install.macos
  ~/.config/install.macos
fi

ln -fs ~/.config/editorconfig ~/.editorconfig
ln -fs ~/.config/tern/tern_config ~/.tern-config
ln -fs ~/.config/tmux/config ~/.tmux.conf

vim +PlugUpgrade +PlugInstall +qall
pip install neovim

cd ~/.local/share/nvim/plugged/tern_for_vim
  npm i
cd -

cd ~/.local/share/nvim/plugged/YouCompleteMe
  ./install.py --tern-completer
cd -

fish -c 'fundle install'
