auto_sync = true
ctrl_n_shortcuts = true
dialect = "uk"
enter_accept = true
filter_mode = "host"
filter_mode_shell_up_key_binding = "session"
inline_height = 5
show_help = false
style = "compact"
workspaces = true

[sync]
records = true
