# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/kd3p8zwk0xibb1s4pp8yrp68w99g15fy-hm-session-vars.fish



status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias eza 'eza --icons'
    alias gh 'op plugin run -- gh'
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'

    # Interactive shell initialisation
    /nix/store/w1w714ssyrqnzlwnvdqqdhrdpnnxybxg-zoxide-0.9.5/bin/zoxide init fish | source

    if test "$TERM" != dumb
        eval (/home/luke/.nix-profile/bin/starship init fish)

    end

    function __fish_command_not_found_handler --on-event fish_command_not_found
        /nix/store/2r78aiq4bfiibskawbi5vwsy2xxnmavg-command-not-found $argv
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/luke/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/csc2lny869byz6v2177qm498wlg22ssp-atuin-18.3.0/bin/atuin init fish | source

    /nix/store/823qi3acdfxnvn0ylygjg6jabx7b4q31-direnv-2.34.0/bin/direnv hook fish | source


end

status is-interactive; and begin
    enable_transience

    # Set QEMU=1 if we're in QEMU
    if command -q systemd-detect-virt; and [ $(systemd-detect-virt) = qemu ]
        set -x QEMU 1
    end
end
