name: "Binary Cache"
on:
  pull_request:
  push:
jobs:
  binary-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: "actions/checkout@v4"
    - uses: "DeterminateSystems/nix-installer-action@main"
    - uses: cachix/cachix-action@v14
      with:
        name: luke-channings
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build packages
      run: |
        nix run --accept-flake-config .#home-manager -- build --flake .#luke
    - name: Build dev shell
      run: |
        nix develop --impure --accept-flake-config --build
