name: CI

on:
  push:
  pull_request:

env:
  IMAGE_NAME: terminal

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          shellcheck -s bash ./install*
  build-docker:
    name: Build Docker image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lukechannings
          password: ${{ secrets.DOCKER_HUB_AUTHTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lukechannings/terminal:latest
