name: "Release"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  binary-cache:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v4"
    - uses: "DeterminateSystems/nix-installer-action@main"
    - uses: cachix/cachix-action@v14
      with:
        name: luke-channings
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build packages
      run: |
        export NIXPKGS_ALLOW_UNFREE=1
        nix run --accept-flake-config .#home-manager -- build --impure --flake .#luke
        tar -chf home-files.tar.xz ./result/home-files
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./home-files.tar.xz
