name: "Template test: darwin-system"
on:
  workflow_dispatch:
jobs:
  template-test:
    runs-on: macos-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: cachix/cachix-action@v14
        with:
          name: luke-channings
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build packages
        run: |
          export NIXPKGS_ALLOW_UNFREE=1

          nix registry add flake:dotfiles "path:$GITHUB_WORKSPACE"

          nix flake new -t .#darwin-system darwin-system
          sudo nix run path:"$(pwd)/darwin-system"#activate --show-trace
